import {Workspace,Problem} from './core.mjs';
const enc=new TextEncoder(),hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join(''),token=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async x=>hex(await crypto.subtle.digest('SHA-256',enc.encode(x)));
const equal=(a,b)=>{if(typeof a!=='string'||typeof b!=='string')return false;let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0};
export async function hashPassword(password,pepper,salt=token()){if(!pepper)throw Error('Password secret is not configured');const key=await crypto.subtle.importKey('raw',enc.encode(password+'\0'+pepper),'PBKDF2',false,['deriveBits']);const hash=hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256));return salt+':'+hash}
const fail=(text,status=400)=>{throw new Problem(text,status)};
const json=(body,status=200,cookie)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(cookie?{'set-cookie':cookie}:{})}});
const cookie=(value,expires=28800)=>`pmo=${value}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${expires}`;
async function readBody(req,max=65536){const declared=Number(req.headers.get('content-length')||0);if(declared>max)fail('ข้อมูลใหญ่เกินกำหนด',413);const reader=req.body?.getReader();if(!reader)fail('ไม่มีข้อมูล');let size=0,parts=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail('ข้อมูลใหญ่เกินกำหนด',413)}parts.push(value)}const bytes=new Uint8Array(size);let pos=0;for(const part of parts){bytes.set(part,pos);pos+=part.length}let data;try{data=JSON.parse(new TextDecoder().decode(bytes))}catch{fail('ข้อมูลไม่ถูกต้อง')}if(!data||typeof data!=='object'||Array.isArray(data))fail('ข้อมูลไม่ถูกต้อง');return data}
async function load(db){const row=await db.prepare('SELECT data,revision FROM pmo_workspace WHERE id=1').first();if(!row)fail('กำลังเตรียมข้อมูลระบบ กรุณาลองอีกครั้ง',503);return {...row,workspace:new Workspace(JSON.parse(row.data))}}
async function getSession(req,db){const tokenValue=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pmo='))?.slice(4)||'';if(!tokenValue)fail('กรุณาเข้าสู่ระบบ',401);const sid=await digest(tokenValue),s=await db.prepare('SELECT * FROM pmo_sessions WHERE id=? AND expires>?').bind(sid,Date.now()).first();if(!s)fail('กรุณาเข้าสู่ระบบ',401);return s}
async function throttle(db,key){const stamp=Date.now();await db.prepare('INSERT INTO pmo_login_limits(id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').bind(key,stamp+300000,stamp,stamp).run();const row=await db.prepare('SELECT count FROM pmo_login_limits WHERE id=?').bind(key).first();if(row.count>10)fail('ลองใหม่ใน 5 นาที',429)}
export async function handle(req,env){try{if(!env.DB)fail('ฐานข้อมูลยังไม่พร้อม',503);const db=env.DB,url=new URL(req.url),route=url.pathname,method=req.method;if(method!=='GET'&&method!=='POST')return json({error:'Method not allowed'},405);if(method==='POST'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)fail('Invalid origin',403)}
if(route==='/api/health')return json({ok:!!(await db.prepare('SELECT id FROM pmo_workspace WHERE id=1').first())});
if(route==='/api/import'&&method==='POST'){if(!env.PMO_IMPORT_TOKEN||!equal(req.headers.get('authorization'),`Bearer ${env.PMO_IMPORT_TOKEN}`))fail('ไม่มีสิทธิ์นำเข้าข้อมูล',403);if(await db.prepare('SELECT id FROM pmo_workspace WHERE id=1').first())fail('ระบบมีข้อมูลแล้ว ไม่อนุญาตให้นำเข้าทับ',409);const data=await readBody(req,2000000),seed=data.workspace,accounts=data.accounts;if(!seed||!Array.isArray(accounts)||!accounts.length||!['projects','members','events','notifications','users'].every(k=>Array.isArray(seed[k])))fail('ชุดข้อมูลไม่ถูกต้อง');const w=new Workspace(seed);for(const u of seed.users)w.state(u);const stmts=[];for(const a of accounts){if(typeof a.id!=='string'||!a.id||a.id.length>100||/\s/.test(a.id)||typeof a.password!=='string'||a.password.length<16||!seed.users.includes(a.id))fail('บัญชีใช้งานจริงต้องมีรหัสผ่านอย่างน้อย 16 ตัวอักษร');stmts.push(db.prepare('INSERT INTO pmo_accounts(id,password) VALUES (?,?)').bind(a.id,await hashPassword(a.password,env.PMO_PASSWORD_PEPPER)))}if(seed.users.some(u=>!accounts.some(a=>a.id===u)))fail('บัญชีที่นำเข้าไม่ครบ');stmts.push(db.prepare('INSERT INTO pmo_workspace(id,revision,data) VALUES (1,0,?)').bind(JSON.stringify(seed)));await db.batch(stmts);return json({ok:true,projects:seed.projects.length,events:seed.events.length,users:accounts.length})}
if(route==='/api/login'&&method==='POST'){const d=await readBody(req);if(typeof d.user!=='string'||typeof d.password!=='string'||d.user.length>100||d.password.length>1024)fail('ข้อมูลบัญชีไม่ถูกต้อง');const key=await digest((req.headers.get('cf-connecting-ip')||'unknown')+'|'+d.user);await throttle(db,key);await throttle(db,await digest('account|'+d.user));const row=await db.prepare('SELECT password FROM pmo_accounts WHERE id=?').bind(d.user).first(),saved=row?.password||('0'.repeat(64)+':'+ '0'.repeat(64)),got=await hashPassword(d.password,env.PMO_PASSWORD_PEPPER,saved.split(':')[0]);if(!row||!equal(saved,got))fail('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',401);const t=token(),sid=await digest(t),csrf=token();await db.batch([db.prepare('INSERT INTO pmo_sessions(id,user,csrf,expires) VALUES (?,?,?,?)').bind(sid,d.user,csrf,Date.now()+28800000),db.prepare('DELETE FROM pmo_login_limits WHERE id=?').bind(key),db.prepare('DELETE FROM pmo_login_limits WHERE id=?').bind(await digest('account|'+d.user)),db.prepare('DELETE FROM pmo_sessions WHERE expires<?').bind(Date.now()),db.prepare('DELETE FROM pmo_login_limits WHERE expires<?').bind(Date.now())]);return json({ok:true},200,cookie(t))}
const session=await getSession(req,db);
if(route==='/api/state'&&method==='GET'){const {workspace}=await load(db);return json({...workspace.state(session.user),csrf:session.csrf})}
if(method!=='POST')fail('Not found',404);if(!equal(req.headers.get('x-csrf-token'),session.csrf))fail('Invalid session request',403);
if(route==='/api/logout'){await db.prepare('DELETE FROM pmo_sessions WHERE id=?').bind(session.id).run();return json({ok:true},200,cookie('',0))}
if(route==='/api/account'){const d=await readBody(req),{workspace,revision}=await load(db);if(workspace.role(d.project,session.user)!=='OWNER')fail('เฉพาะ OWNER สร้างบัญชีสมาชิกได้',403);if(typeof d.user!=='string'||!d.user||d.user.length>100||/\s/.test(d.user)||typeof d.password!=='string'||d.password.length<16||d.password.length>1024)fail('ระบุชื่อผู้ใช้และรหัสผ่านอย่างน้อย 16 ตัวอักษร');if(await db.prepare('SELECT id FROM pmo_accounts WHERE id=?').bind(d.user).first())fail('มีบัญชีนี้แล้ว ให้เพิ่มสมาชิกด้วยบัญชีเดิม',409);workspace.data.users.push(d.user);workspace.act(session.user,'member',{project:d.project,user:d.user,role:d.role});const hashed=await hashPassword(d.password,env.PMO_PASSWORD_PEPPER);const results=await db.batch([db.prepare('INSERT INTO pmo_accounts(id,password) SELECT ?,? WHERE EXISTS (SELECT 1 FROM pmo_workspace WHERE id=1 AND revision=?)').bind(d.user,hashed,revision),db.prepare('UPDATE pmo_workspace SET data=?,revision=revision+1 WHERE id=1 AND revision=?').bind(JSON.stringify(workspace.data),revision)]);if(results[1].meta.changes!==1)fail('มีการแก้ไขพร้อมกัน กรุณาลองอีกครั้ง',409);return json({ok:true})}
if(route==='/api/action'){const d=await readBody(req),{workspace,revision}=await load(db);workspace.act(session.user,d.action,d);const result=await db.prepare('UPDATE pmo_workspace SET data=?,revision=revision+1 WHERE id=1 AND revision=?').bind(JSON.stringify(workspace.data),revision).run();if(result.meta.changes!==1)fail('มีสมาชิกอื่นแก้ไขข้อมูลพร้อมกัน กรุณาลองบันทึกอีกครั้ง',409);return json({ok:true})}
if(route==='/api/export'){const {workspace}=await load(db),accessible=workspace.state(session.user).projects;if(!accessible.length)fail('ไม่มีโครงการให้ส่งออก',403);const ids=new Set(accessible.map(p=>p.id));return json({exportedAt:new Date().toISOString(),projects:workspace.data.projects.filter(p=>ids.has(p.id)),events:workspace.data.events.filter(e=>ids.has(e.project))})}
fail('Not found',404)
}catch(e){if(e instanceof Problem)return json({error:e.message},e.status);console.error('PMO request failed',e instanceof Error?e.message:'unknown error');return json({error:'ระบบบันทึกข้อมูลไม่สำเร็จ กรุณาลองอีกครั้ง ข้อมูลที่กรอกยังอยู่'},500)}}
