import meta from './meta.json' with {type:'json'};
export {meta};
meta.controlModules.acceptance??={label:'ตรวจรับ',phase:'Acceptance',fields:[['title','รายการตรวจรับ','text'],['owner','ผู้รับผิดชอบ','member'],['due','กำหนดตรวจรับ','date'],['status','สถานะ','status'],['evidence','หลักฐาน / เลขที่หนังสือ','textarea'],['notes','รอใคร / ติดอะไร / หมายเหตุ','textarea'],['kind','ประเภท','select',['DELIVERY_REVIEW','CUSTOMER_REPLY','ACCEPTANCE']],['milestoneId','งวดงานที่ผูก','milestone'],['customerReplyRef','เลขที่/วันที่ตอบกลับ','text'],['customerAcceptedDate','วันที่ลูกค้าเซ็นต์รับมอบ','date']]};
export class Problem extends Error{constructor(message,status=400){super(message);this.status=status}}
const fail=(message,status=400)=>{throw new Problem(message,status)};
const clone=x=>structuredClone(x),id=()=>crypto.randomUUID().replaceAll('-',''),now=()=>new Date().toISOString();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const text=(v,max=10000)=>{if(typeof v!=='string'||v.length>max)fail('ข้อความไม่ถูกต้องหรือยาวเกินไป');return v.trim()};
const required=(d,k,max=200)=>text(d[k]??'',max)||fail('ข้อมูลไม่ถูกต้อง: '+k);
export function validDate(v){if(v==='')return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail('วันที่ไม่ถูกต้อง');return v}
export function parseDay(value){const v=String(value||'').trim(),months=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];let out=v;try{if(v.includes('/')){let [d,m,y]=v.split('/').map(Number);if(y>2400)y-=543;out=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}else if(months.some(m=>v.includes(m))){let [d,m,y]=v.split(/\s+/);y=Number(y);if(y>2400)y-=543;out=`${y}-${String(months.indexOf(m)+1).padStart(2,'0')}-${d.padStart(2,'0')}`}return validDate(out)||null}catch{return null}}
const daydiff=(a,b)=>(Date.parse(a)-Date.parse(b))/86400000;
const dayadd=(v,n)=>new Date(Date.parse(v)+n*86400000).toISOString().slice(0,10);
const enumValue=(v,allowed,label='สถานะ')=>allowed.includes(v)?v:fail(label+'ไม่ถูกต้อง');
const money=(v)=>{if(v===null||v==='')return null;const n=Number(v);if(!['number','string'].includes(typeof v)||!Number.isFinite(n)||n<0||n>1e12)fail('จำนวนเงินไม่ถูกต้อง');return Math.round(n*100)/100};
const defaultInfo=name=>({contractName:name,contractNo:'',signedDate:'',projectStartDate:'',deliveryDueDate:'',projectCode:'',contractValue:null});
const defaultCrisis=()=>({active:false,originalOwner:'',actingOwner:'',reason:'',criticalNextActions:'',waiting:'',contacts:'',links:'',latestCommunication:'',activatedAt:'',acceptedAt:'',closedAt:''});
const defaultMilestoneLabels=()=>Object.fromEntries(meta.milestoneFields.map((key,i)=>[key,['งวดงานที่','งวดเงินที่','สัดส่วนเงิน (%)','งวดตามสัญญา','สิ่งส่งมอบ','ขอบเขตของงาน','ข้อในสัญญา','กำหนดส่งมอบ (ตามสัญญา)','วัน','กำหนดส่งมอบ (ตาม TOR)','กำหนดส่งมอบ (ตามแผน)','เดือน','วันที่ส่งมอบ','เลขที่/วันที่ จดหมาย','เลขที่/วันที่ หนังสือตอบกลับ (ลูกค้า)','วันที่เซ็นต์รับมอบ (ลูกค้า)','สถานะ'][i]]));
const completeDelivery=new Set(['DELIVERED','WAITING_REPLY','WAITING_ACCEPTANCE','ACCEPTED']);
export function deliverySummary(p,day=today()){
 const rows=p.milestones||[],done=rows.filter(r=>completeDelivery.has(r.status)),pending=rows.filter(r=>!completeDelivery.has(r.status));
 const current=pending.find(r=>r.status==='IN_PROGRESS')||pending[0]||null,currentIndex=current?rows.findIndex(r=>r.id===current.id):-1;
 const next=current?pending.find(r=>rows.findIndex(x=>x.id===r.id)>currentIndex)||null:null;
 return {total:rows.length,done:done.length,accepted:rows.filter(r=>r.status==='ACCEPTED').length,percent:rows.length?Math.round(done.length*1000/rows.length)/10:0,current,next,overdue:pending.filter(r=>(parseDay(r.planDue||r.torDue)||'9999-12-31')<day).map(r=>r.id),blocked:pending.filter(r=>r.status==='BLOCKED').map(r=>r.id)}
}
export function paymentSummary(p){const total=Math.round(p.milestones.reduce((s,m)=>s+Number(m.paymentPercent||0),0)*10000)/10000,groups=Object.create(null);const value=p.projectInfo.contractValue??null;for(const m of p.milestones){const no=String(m.paymentNo||'').trim(),percent=Number(m.paymentPercent||0);if(no&&percent){groups[no]??={percent:0,workNos:[]};groups[no].percent+=percent;groups[no].workNos.push(m.workNo)}}for(const g of Object.values(groups)){g.percent=Math.round(g.percent*10000)/10000;g.amount=value===null?null:Math.round(value*g.percent)/100}return {totalPercent:total,remainingPercent:Math.round((100-total)*10000)/10000,complete:Math.abs(total-100)<.0001,contractValue:value,groups}}
export function lifecycleChecks(p){return Object.fromEntries(Object.entries(meta.checks).map(([phase,items])=>[phase,items.map(([id,title,required])=>({id,title,required,...p.checks?.[id]}))]))}
export function closureBlockers(p){const out=[];if(p.phase!=='Closure')out.push('เปลี่ยน Phase เป็นปิดโครงการก่อน');if(p.tasks.some(t=>t.status!=='DONE'))out.push('ยังมีงานย่อยไม่เสร็จ');if(p.milestones.some(m=>m.status!=='ACCEPTED'))out.push('ยังมีงวดงานที่ไม่ยืนยันตรวจรับ');if((p.controls.risk||[]).some(r=>r.status!=='DONE'))out.push('ยังมีความเสี่ยงที่ไม่ปิด');if((p.controls.finance||[]).some(r=>r.status!=='DONE'))out.push('ยังมีรายการการเงินไม่เสร็จ');const checks=lifecycleChecks(p);for(const phase of ['Acceptance','Billing','Closure'])for(const c of checks[phase])if(c.required&&(c.status!=='DONE'||!c.evidence))out.push(c.title);return out}
export function controlSummary(p,day=today()){const records=p.controls||{},alerts=[],alert=(module,title,r={})=>alerts.push({module,title,id:r.id||''}),end=parseDay(p.projectInfo.deliveryDueDate),signed=parseDay(p.projectInfo.signedDate);
for(const r of records.procurement||[]){const start=parseDay(r.startDate),po=parseDay(r.poDate),vendEnd=parseDay(r.endDate);if(start&&po&&start<po)alert('procurement','สัญญา Vendor เริ่มก่อนวันที่ PO',r);if(end&&vendEnd&&daydiff(end,vendEnd)<15)alert('procurement','สัญญา Vendor มีระยะเผื่อก่อนจบสัญญาลูกค้าน้อยกว่า 15 วัน',r);if(r.period&&['VENDOR_PROGRESS','ACCOUNTING_REPORT'].includes(r.kind)){const [y,m]=r.period.split('-').map(Number),last=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10),due=r.kind==='VENDOR_PROGRESS'?last:dayadd(last,5),completed=parseDay(r.completedDate);if(completed?completed>due:due<day)alert('procurement','รายงานรอบ '+r.period+' เลยกำหนด '+due,r)}}
if(signed){if(daydiff(day,signed)>15&&!(records.opening||[]).some(r=>r.kind==='STAMP_DUTY'&&r.status==='DONE'))alert('opening','ยังไม่มีหลักฐานอากรแสตมป์ที่ยืนยันเสร็จ ภายในกรอบ 15 วันตามกระบวนการ');const [y,m,d]=signed.split('-').map(Number),next=new Date(Date.UTC(y,m,Math.min(d,new Date(Date.UTC(y,m+1,0)).getUTCDate()))).toISOString().slice(0,10);if(next<day&&p.checks?.risk_assessment?.status!=='DONE')alert('risk','ยังไม่ยืนยันการประเมินความเสี่ยงภายใน 1 เดือนตามกระบวนการ')}
for(const [module,rows] of Object.entries(records))for(const r of rows){if(r.status==='DONE')continue;if(module==='risk'&&['HIGH','CRITICAL'].includes(r.severity))alert(module,'ความเสี่ยงสูง: '+r.title,r);if(r.status==='BLOCKED')alert(module,'ติดขัด: '+r.title,r);else if((parseDay(r.due)||'9999-12-31')<day)alert(module,'เกินกำหนด: '+r.title,r)}
const finance=records.finance||[],total=kind=>finance.filter(r=>r.kind===kind&&r.status==='DONE').reduce((s,r)=>s+(r.amount||0),0),received=total('CUSTOMER_PAYMENT'),paid=total('VENDOR_PAYMENT');return {alerts,openRisks:(records.risk||[]).filter(r=>r.status!=='DONE').length,received,paid,net:received-paid,financeRecorded:finance.length>0}}
export function health(p){
 const day=today(),active=p.tasks.filter(t=>t.status!=='DONE'),delivery=deliverySummary(p),out=(status,reason,target={view:'tor'})=>({status,reason,target});
 if(p.completed)return out('COMPLETED','ปิดโครงการแล้ว',{view:'closure'});
 const blocked=active.find(t=>t.status==='BLOCKED');if(blocked)return out('BLOCKED',blocked.waiting,{view:'tasks',type:'task',id:blocked.id});
 if(delivery.blocked.length)return out('BLOCKED','มีงวดส่งมอบติดปัญหา',{view:'tor',type:'milestone',id:delivery.blocked[0]});
 for(const [module,rows] of Object.entries(p.controls||{})){const r=rows.find(r=>r.status==='BLOCKED');if(r)return out('BLOCKED','มีรายการควบคุมโครงการติดขัด',{view:module,type:'control',id:r.id})}
 if(delivery.overdue.length)return out('OVERDUE','มีงวดส่งมอบเกินกำหนดตามแผน',{view:'tor',type:'milestone',id:delivery.overdue[0]});
 const late=active.find(t=>t.due&&t.due<day);if(late)return out('OVERDUE','มีงานเกินกำหนด',{view:'tasks',type:'task',id:late.id});
 if(p.due&&p.due<day)return out('OVERDUE','โครงการเกินกำหนดส่ง',{view:'planning'});
 const watch=active.find(t=>t.priority==='HIGH'||t.status==='WAITING'||(t.due&&daydiff(t.due,day)>=0&&daydiff(t.due,day)<=3));if(watch)return out('AT RISK','มีงานสำคัญ ใกล้กำหนด หรือรอการตอบกลับ',{view:'tasks',type:'task',id:watch.id});
 const alert=controlSummary(p).alerts[0];if(alert){const target=alert.id?{view:alert.module,type:'control',id:alert.id}:alert.module==='opening'?{view:'opening',type:'control',kind:'STAMP_DUTY'}:{view:'lifecycle',type:'checklist',phase:'Planning',id:'risk_assessment'};return out('AT RISK',alert.title,target)}
 return out('ON TRACK','ไม่มีงานเกินกำหนดหรือ blocker ที่บันทึกไว้');
}
function normalize(field,value){if(field==='paymentPercent'){const n=Number(value||0);if(!Number.isFinite(n)||n<0||n>100)fail('สัดส่วนเงินต้องอยู่ระหว่าง 0–100%');return Math.round(n*10000)/10000}if(field==='status')return enumValue(String(value||''),meta.milestoneStatuses,'สถานะงวดงาน');return text(String(value??''),['deliverables','scope','contractMilestone'].includes(field)?10000:2000)}
function validateRows(p){if(paymentSummary(p).totalPercent>100.0001)fail('สัดส่วนงวดเงินรวมกันเกิน 100%');for(const m of p.milestones)if(m.status==='ACCEPTED'&&!(m.evidence?.trim()||m.customerAcceptedDate))fail('ระบุหลักฐานหรือวันตรวจรับก่อนยืนยันตรวจรับแล้ว')}
function validateBackToBack(p){const rows=p.controls.finance||[],receipts=new Map(rows.filter(r=>r.kind==='CUSTOMER_PAYMENT'&&r.status==='DONE').map(r=>[r.id,r])),allocated={};for(const r of rows)if(r.kind==='VENDOR_PAYMENT'&&r.condition==='BACK_TO_BACK'&&r.status==='DONE'){const receipt=receipts.get(r.customerPaymentId);if(!receipt)fail('Back-to-back ต้องมีรายการรับเงินลูกค้าที่ยืนยันแล้ว');if(!receipt.completedDate||receipt.completedDate>r.completedDate)fail('วันที่จ่าย Vendor ต้องไม่ก่อนวันที่รับเงินลูกค้า');allocated[receipt.id]=(allocated[receipt.id]||0)+(r.amount||0);if(allocated[receipt.id]>(receipt.amount||0))fail('ยอดจ่าย Back-to-back รวมเกินเงินลูกค้าที่อ้างอิง')}}
export class Workspace{
constructor(data){this.data=clone(data)}
role(pid,user){return this.data.members.find(m=>m.project===pid&&m.user===user)?.role||fail('คุณไม่มีสิทธิ์เข้าถึงโครงการนี้',403)}
 isAdmin(user){return (this.data.systemAdmins||[]).includes(user)||user==='admin'}
 project(pid,user,write=false){const role=this.role(pid,user);if(write&&role==='VIEWER')fail('VIEWER ดูข้อมูลได้อย่างเดียว',403);const p=this.data.projects.find(p=>p.id===pid)||fail('ไม่พบโครงการ',404);for(const [key,value] of Object.entries({allowEditorInvites:false,tasks:[],handover:'',handoverDetails:{},crisis:defaultCrisis(),milestone:'',due:'',completed:false,projectInfo:defaultInfo(p.name),milestones:[],controls:{},checks:{},milestoneLabels:defaultMilestoneLabels()}))p[key]??=value;return p}
event(project,actor,action,detail){this.data.events.push({id:Math.max(0,...this.data.events.map(e=>e.id))+1,project,actor,action,detail:JSON.stringify(detail),at:now()})}
notify(project,user,text){this.data.notifications.push({id:Math.max(0,...this.data.notifications.map(n=>n.id))+1,project,user,text,seen:0})}
 state(user){const isAdmin=this.isAdmin(user),projects=this.data.members.filter(m=>m.user===user).map(m=>{const p=clone(this.project(m.project,user));return {...p,role:m.role,members:this.data.members.filter(x=>x.project===p.id).map(({project,...x})=>x),events:this.data.events.filter(e=>e.project===p.id).slice(-300).reverse(),deliverySummary:deliverySummary(p),lifecycleChecks:lifecycleChecks(p),closureBlockers:closureBlockers(p),controlSummary:controlSummary(p),health:health(p),paymentSummary:paymentSummary(p)}});const ids=new Set(projects.map(p=>p.id)),users=isAdmin?[...new Set([...(this.data.users||[]),...(this.data.userRecords||[]).map(x=>typeof x==='string'?x:x.user)])].filter(Boolean).map(name=>{const rec=(this.data.userRecords||[]).find(x=>x?.user===name);return rec?clone(rec):{user:name,createdBy:'เดิม',createdAt:'',disabled:false}}):[];const adminProjects=isAdmin?this.data.projects.map(p=>({id:p.id,name:p.name,projectCode:p.projectInfo?.projectCode||'',phase:p.phase,members:this.data.members.filter(m=>m.project===p.id).map(({project,...m})=>m)})):[];return {user,isAdmin,projects,adminProjects,users,adminEvents:isAdmin?this.data.events.filter(e=>!e.project||e.action==='admin_membership').slice(-200).reverse():[],notifications:this.data.notifications.filter(n=>n.user===user&&ids.has(n.project)).slice(-100).reverse(),phases:meta.phases,phaseLabels:meta.phaseLabels,controlModules:meta.controlModules,statuses:meta.statuses,milestoneStatuses:meta.milestoneStatuses}}
act(user,action,d){const before=clone(this.data);try{return this.apply(user,action,d)}catch(e){this.data=before;throw e}}
apply(user,action,d){
if(action==='create_project'){const name=required(d,'name'),p={id:id(),name,phase:'Contract',tasks:[],handover:'',handoverDetails:{},crisis:defaultCrisis(),milestone:'',due:'',completed:false,projectInfo:defaultInfo(name),milestones:[],controls:{},checks:{},milestoneLabels:defaultMilestoneLabels()};this.data.projects.push(p);this.data.members.push({project:p.id,user,role:'OWNER',addedBy:user,grantedBy:user});this.event(p.id,user,action,{name});return}
if(action==='milestone_header'||action==='milestone_headers'){const pid=required(d,'project'),p=this.project(pid,user,true);if(!['OWNER','EDITOR'].includes(this.role(pid,user)))fail('ไม่มีสิทธิ์แก้หัวตาราง',403);p.milestoneLabels??=defaultMilestoneLabels();const changes=action==='milestone_header'?[{field:d.field,label:d.label}]:d.labels;if(!Array.isArray(changes)||!changes.length||changes.length>meta.milestoneFields.length)fail('ข้อมูลหัวตารางไม่ถูกต้อง');for(const item of changes){const field=required(item,'field'),label=required(item,'label',200);if(!meta.milestoneFields.includes(field))fail('คอลัมน์ไม่ถูกต้อง');const before=p.milestoneLabels[field]||field;if(before!==label){p.milestoneLabels[field]=label;this.event(pid,user,'milestone_header',{field,before,after:label})}}return}
if(action==='admin_membership'){if(!this.isAdmin(user))fail('เฉพาะ System Admin จัดการสมาชิกทุกโครงการได้',403);const pid=required(d,'project'),target=required(d,'user'),newrole=enumValue(d.role,['OWNER','EDITOR','VIEWER','REMOVE'],'สิทธิ์');if(!this.data.projects.some(p=>p.id===pid))fail('ไม่พบโครงการ',404);const old=this.data.members.find(m=>m.project===pid&&m.user===target);if(old?.role==='OWNER'&&newrole!=='OWNER'&&this.data.members.filter(m=>m.project===pid&&m.role==='OWNER').length===1)fail('ต้องเหลือ OWNER อย่างน้อยหนึ่งคน');if(!this.data.users.includes(target))fail('ไม่พบบัญชีนี้');this.data.members=this.data.members.filter(m=>!(m.project===pid&&m.user===target));if(newrole!=='REMOVE')this.data.members.push({project:pid,user:target,role:newrole,addedBy:old?.addedBy||user,grantedBy:user});this.event(pid,user,'admin_membership',{user:target,before:old?.role||null,after:newrole});this.event('',user,'admin_membership',{project:pid,user:target,before:old?.role||null,after:newrole});return}
if(action==='read_notice'){const n=this.data.notifications.find(n=>n.id===Number(d.id)&&n.user===user);if(n)n.seen=1;return}
const pid=required(d,'project'),p=this.project(pid,user,true),role=this.role(pid,user);if(p.completed&&!['project','member'].includes(action))fail('เปิดโครงการอีกครั้งก่อนแก้ไขข้อมูล');
if(action==='member'){const target=required(d,'user'),newrole=enumValue(d.role,['OWNER','EDITOR','VIEWER','REMOVE'],'สิทธิ์'),old=this.data.members.find(m=>m.project===pid&&m.user===target);if(role==='EDITOR'&&(old||!['EDITOR','VIEWER'].includes(newrole)))fail('EDITOR เพิ่มสมาชิกใหม่ได้เฉพาะ EDITOR หรือ VIEWER',403);if(!['OWNER','EDITOR'].includes(role))fail('ไม่มีสิทธิ์จัดการสมาชิกนี้',403);if(!this.data.users.includes(target))fail('ไม่พบบัญชีนี้ ให้ System Admin สร้างบัญชีก่อน');if(old?.role==='OWNER'&&newrole!=='OWNER'&&this.data.members.filter(m=>m.project===pid&&m.role==='OWNER').length===1)fail('ต้องเหลือ OWNER อย่างน้อยหนึ่งคน');this.data.members=this.data.members.filter(m=>!(m.project===pid&&m.user===target));if(newrole!=='REMOVE')this.data.members.push({project:pid,user:target,role:newrole,addedBy:old?.addedBy||user,grantedBy:user});this.event(pid,user,action,{user:target,before:old?.role||null,after:newrole});return}
if(action==='control'){const module=required(d,'module'),config=(Object.hasOwn(meta.controlModules,module)?meta.controlModules[module]:null)||fail('หมวดไม่ถูกต้อง'),rows=p.controls[module]??=[],rid=d.id||id(),old=rows.find(r=>r.id===rid);if(d.id&&!old)fail('ไม่พบรายการ',404);const record={id:rid,comments:clone(old?.comments||[])};for(const [key,label,type,choices] of config.fields){let value=d[key]??'';if(type==='money')value=money(value);else if(type==='date')value=validDate(value);else if(type==='month'){if(value)validDate(value+'-01')}else if(type==='select')enumValue(value,choices,label);else if(type==='status')enumValue(value,meta.statuses);else if(type==='member'){value=text(value,100);if(value)this.role(pid,value)}else value=text(value);record[key]=value}record.title=required(d,'title',500);if(['WAITING','BLOCKED'].includes(record.status)&&!record.notes)fail('ระบุสิ่งที่รอ / ติดขัดในรายละเอียด');if(record.status==='DONE'&&!record.evidence)fail('ระบุหลักฐานก่อนยืนยันเสร็จ');const related=new Set([...Object.values(p.controls).flat(),...p.milestones,...p.tasks].map(r=>r.id));if(record.relatedId&&!related.has(record.relatedId))fail('รายการอ้างอิงต้องอยู่ในโครงการเดียวกัน');if(record.milestoneId&&!p.milestones.some(m=>m.id===record.milestoneId))fail('ไม่พบงวดงานที่อ้างอิง');if(module==='finance'&&record.status==='DONE'&&['CUSTOMER_PAYMENT','VENDOR_PAYMENT'].includes(record.kind)&&(record.amount===null||!record.completedDate))fail('ระบุจำนวนเงินและวันที่รับ/จ่ายจริง');record.updated=now();p.controls[module]=old?rows.map(r=>r.id===rid?record:r):[...rows,record];validateBackToBack(p);this.event(pid,user,action,{module,id:rid,title:record.title,before:old||null,after:record});if(record.owner&&old?.owner!==record.owner)this.notify(pid,record.owner,'ได้รับมอบหมาย: '+record.title);return}
if(action==='checklist'){const key=required(d,'id'),template=Object.values(meta.checks).flat().find(c=>c[0]===key)||fail('Checklist ไม่ถูกต้อง'),status=enumValue(d.status,meta.statuses),owner=text(d.owner||'',100),evidence=text(d.evidence||''),notes=text(d.notes||'');if(owner)this.role(pid,owner);if(status==='DONE'&&!evidence)fail('ระบุหลักฐาน หรือเหตุผลที่ไม่เกี่ยวข้อง ก่อนยืนยันเสร็จ');if(['WAITING','BLOCKED'].includes(status)&&!notes)fail('ระบุสิ่งที่รอ / ติดขัด');const before=p.checks[key]||null,after={status,owner,due:validDate(d.due||''),evidence,notes,updated:now()};p.checks[key]=after;this.event(pid,user,action,{id:key,before,after});if(owner&&before?.owner!==owner)this.notify(pid,owner,'ได้รับมอบหมาย: '+template[1]);return}
if(action==='project'){if(role!=='OWNER')fail('เฉพาะ OWNER เปลี่ยนการตั้งค่าโครงการได้',403);Object.assign(p,{name:required(d,'name'),phase:enumValue(d.phase,meta.phases,'Phase'),milestone:text(d.milestone||'',500),due:validDate(d.due||'')});const completed=d.completed===true;if(completed&&closureBlockers(p).length)fail('ยังปิดโครงการไม่ได้: '+closureBlockers(p).join('; '));p.completed=completed}
else if(action==='project_info'){if(role!=='OWNER')fail('เฉพาะ OWNER แก้ข้อมูลสัญญาหลักได้',403);const before=clone(p.projectInfo);for(const key of meta.projectInfoFields)if(key in d)p.projectInfo[key]=key==='contractValue'?money(d[key]):text(String(d[key]??''),2000);if(p.projectInfo.contractName)p.name=p.projectInfo.contractName;const changes=Object.fromEntries(meta.projectInfoFields.filter(k=>before[k]!==p.projectInfo[k]).map(k=>[k,{before:before[k],after:p.projectInfo[k]}]));if(Object.keys(changes).length)this.event(pid,user,action,{changes});return}
else if(action==='milestone_add'){const row=Object.fromEntries(meta.milestoneFields.map(k=>[k,'']));Object.assign(row,{id:id(),workNo:String(Math.max(0,...p.milestones.map(r=>/^\d+$/.test(r.workNo)?Number(r.workNo):0))+1),status:'NOT_DUE',paymentPercent:0});p.milestones.push(row);this.event(pid,user,action,{id:row.id,workNo:row.workNo});return}
else if(action==='milestone_details'){const row=p.milestones.find(m=>m.id===d.id)||fail('ไม่พบงวดงาน',404),before=clone(row),owner=text(d.owner||'',100);if(owner)this.role(pid,owner);Object.assign(row,{owner,status:normalize('status',d.status??row.status),next:text(d.next||'',2000),waiting:text(d.waiting||'',2000),handover:text(d.handover||''),evidence:text(d.evidence||'')});if(row.status==='BLOCKED'&&!row.waiting)fail('ระบุสิ่งที่ติดขัด');validateRows(p);this.event(pid,user,action,{id:row.id,workNo:row.workNo,before,after:row});if(owner&&before.owner!==owner)this.notify(pid,owner,'ได้รับมอบหมายงวดงาน '+row.workNo);return}
else if(['milestone_cell','milestone_cells'].includes(action)){const cells=action==='milestone_cell'?[d]:d.cells;if(!Array.isArray(cells)||!cells.length||cells.length>500)fail('วางได้ไม่เกิน 500 ช่องต่อครั้ง');const changes=[];for(const c of cells){if(!c||!meta.milestoneFields.includes(c.field))fail('คอลัมน์ไม่ถูกต้อง');const row=p.milestones.find(m=>m.id===c.id)||fail('ไม่พบงวดงาน',404),before=row[c.field]??'',after=normalize(c.field,c.value);row[c.field]=after;if(before!==after)changes.push({id:row.id,workNo:row.workNo,field:c.field,before,after,reason:action==='milestone_cells'?'วางข้อมูลหลายช่อง':text(d.reason||'',500)})}validateRows(p);for(const change of changes)this.event(pid,user,'milestone_cell',change);return}
else if(action==='milestone_delete'){const mid=required(d,'id'),row=p.milestones.find(m=>m.id===mid)||fail('ไม่พบงวดงาน',404);if(Object.values(p.controls).flat().some(r=>r.relatedId===mid||r.milestoneId===mid))fail('ย้ายเอกสารหรือการเงินที่อ้างอิงงวดนี้ก่อนลบ');p.milestones=p.milestones.filter(m=>m.id!==mid);this.event(pid,user,action,{id:mid,workNo:row.workNo});return}
else if(action==='handover'){if(d.details&&typeof d.details==='object'&&!Array.isArray(d.details)){const keys=['status','done','remaining','next','waiting','links'],before=clone(p.handoverDetails||{}),after=Object.fromEntries(keys.map(k=>[k,text(d.details[k]||'',4000)]));if(!after.status&&!after.done&&!after.remaining&&!after.next&&!after.waiting&&!after.links)fail('เพิ่มข้อมูลสำหรับส่งต่องานอย่างน้อยหนึ่งรายการ');p.handoverDetails=after;this.event(pid,user,action,{before,after});return}p.handover=required(d,'text',10000)}
else if(action==='crisis_handover'){const before=clone(p.crisis||defaultCrisis()),active=d.active===true||d.active==='true'||d.active==='on',originalOwner=text(d.originalOwner||'',100),actingOwner=text(d.actingOwner||'',100);if(originalOwner)this.role(pid,originalOwner);if(actingOwner)this.role(pid,actingOwner);if(active&&(!originalOwner||!actingOwner))fail('ระบุเจ้าของงานเดิมและผู้รับช่วงเมื่อเปิด Crisis Handover');const after={...defaultCrisis(),active,originalOwner,actingOwner,reason:text(d.reason||'',4000),criticalNextActions:text(d.criticalNextActions||'',4000),waiting:text(d.waiting||'',4000),contacts:text(d.contacts||'',4000),links:text(d.links||'',4000),latestCommunication:text(d.latestCommunication||'',4000),activatedAt:before.activatedAt||'',acceptedAt:before.acceptedAt||'',closedAt:before.closedAt||''};if(active&&!after.reason)fail('ระบุเหตุผลที่ต้องส่งต่องานฉุกเฉิน');if(active&&!after.criticalNextActions)fail('ระบุ Critical Next Actions อย่างน้อยหนึ่งรายการ');if(active&&!before.active){after.activatedAt=now();after.acceptedAt='';after.closedAt=''}if(active&&before.actingOwner!==actingOwner)after.acceptedAt='';if(!active&&before.active)after.closedAt=now();p.crisis=after;this.event(pid,user,action,{before,after});if(active&&actingOwner&&(!before.active||before.actingOwner!==actingOwner))this.notify(pid,actingOwner,'ได้รับมอบหมายให้รับช่วงโครงการแบบ Crisis Handover');return}
else if(action==='crisis_accept'){const current=p.crisis||defaultCrisis();if(!current.active)fail('โครงการไม่ได้อยู่ใน Crisis Handover');if(current.actingOwner!==user)fail('เฉพาะผู้รับช่วงที่ระบุเท่านั้นที่รับช่วงงานได้',403);if(!current.acceptedAt){const before=clone(current);current.acceptedAt=now();p.crisis=current;this.event(pid,user,action,{before,after:clone(current)});if(current.originalOwner&&current.originalOwner!==user)this.notify(pid,current.originalOwner,user+' รับช่วงโครงการแล้ว')}return}
else if(action==='task'){const tid=d.id||id(),old=p.tasks.find(t=>t.id===tid);if(d.id&&!old)fail('ไม่พบงาน',404);const status=enumValue(d.status||'TODO',meta.statuses),priority=enumValue(d.priority||'NORMAL',['HIGH','NORMAL','LOW'],'ความสำคัญ'),owner=required(d,'owner'),backup=text(d.backupOwner||'',100),waiting=text(d.waiting||'',1000),deps=d.dependencies||[];this.role(pid,owner);if(backup)this.role(pid,backup);if(['WAITING','BLOCKED'].includes(status)&&!waiting)fail('กรุณาระบุว่ารอใครหรือมีอะไรติดขัด');if(!Array.isArray(deps)||deps.some(x=>typeof x!=='string'||!p.tasks.some(t=>t.id===x)||x===tid))fail('Dependency ต้องเป็นงานอื่นในโครงการเดียวกัน');const graph=Object.fromEntries(p.tasks.map(t=>[t.id,t.dependencies]));graph[tid]=deps;const visit=(n,path)=>{if(path.has(n))fail('Dependency วนกลับมาที่งานเดิม');for(const child of graph[n]||[])visit(child,new Set([...path,n]))};visit(tid,new Set());if(status==='DONE'&&p.tasks.some(t=>deps.includes(t.id)&&t.status!=='DONE'))fail('งานที่ต้องทำก่อนยังไม่เสร็จ');if(old?.status==='DONE'&&status!=='DONE'&&p.tasks.some(t=>t.status==='DONE'&&t.dependencies.includes(tid)))fail('เปิดงานที่อ้างอิงงานนี้อีกครั้งก่อน');const task={id:tid,title:required(d,'title'),owner,backupOwner:backup,doneNote:text(d.doneNote||'',4000),remainingNote:text(d.remainingNote||'',4000),due:validDate(d.due||''),status,priority,waiting,next:text(d.next||'',2000),evidence:text(d.evidence||'',2000),dependencies:deps,comments:clone(old?.comments||[]),updated:now()};p.tasks=old?p.tasks.map(t=>t.id===tid?task:t):[...p.tasks,task];if(old?.owner!==owner)this.notify(pid,owner,'ได้รับมอบหมาย: '+task.title)}
else if(action==='comment'){const type=d.targetType||'task',items=type==='task'?p.tasks:type==='milestone'?p.milestones:Object.hasOwn(meta.controlModules,type)?p.controls[type]||[]:fail('ประเภทความคิดเห็นไม่ถูกต้อง'),record=items.find(r=>r.id===d.id)||fail('ไม่พบรายการ',404),comment={author:user,text:required(d,'text',4000),at:now()};(record.comments??=[]).push(comment);const mentioned=new Set(comment.text.split(/\s+/).filter(w=>w.startsWith('@')).map(w=>w.slice(1)));for(const m of this.data.members.filter(m=>m.project===pid))if(mentioned.has(m.user))this.notify(pid,m.user,user+' กล่าวถึงคุณ: '+(record.title||'งวด '+record.workNo))}
else fail('ไม่รู้จักคำสั่ง');this.event(pid,user,action,d);
}
}
