import test from 'node:test';import assert from 'node:assert/strict';
import {Workspace,meta,Problem,parseDay,deliverySummary,controlSummary} from '../lib/pmo/core.mjs';
function setup(){const w=new Workspace({users:['owner','editor','viewer','outsider'],projects:[],members:[],events:[],notifications:[]});w.act('owner','create_project',{name:'Test'});const p=w.data.projects[0];for(const [user,role] of [['editor','EDITOR'],['viewer','VIEWER']])w.act('owner','member',{project:p.id,user,role});const act=(action,d={},user='owner')=>w.act(user,action,{project:p.id,...d}),project=()=>w.state('owner').projects[0];const record=(module,d={})=>{const fields=Object.fromEntries(meta.controlModules[module].fields.map(([k,l,t,choices])=>[k,t==='select'?choices[0]:t==='status'?'TODO':'']));act('control',{...fields,title:'Record',owner:'editor',module,...d});return project().controls[module].at(-1)};return {w,p,act,project,record}}
test('Every lifecycle module persists with audit and assignments',()=>{const {w,record,project}=setup();for(const module of Object.keys(meta.controlModules)){record(module);assert.equal(project().events[0].action,'control')}assert.equal(w.state('editor').notifications.length,7)});
test('Viewer and outsider cannot mutate data',()=>{const {act}=setup();for(const user of ['viewer','outsider'])for(const [action,d] of [['milestone_add',{}],['control',{module:'risk'}],['checklist',{id:'project_open',status:'DONE',evidence:'proof'}]])assert.throws(()=>act(action,d,user),e=>e.status===403)});
test('Cross-project state and mention notifications stay isolated',()=>{const {w,act,record}=setup();const r=record('risk');act('comment',{targetType:'risk',id:r.id,text:'@viewer @outsider'});assert.equal(w.state('outsider').projects.length,0);assert.equal(w.state('outsider').notifications.length,0);assert.equal(w.state('viewer').notifications.length,1)});
test('Three delivered milestones mean 60% progress, not acceptance or receipts',()=>{const {act,project}=setup();for(const status of ['DELIVERED','DELIVERED','DELIVERED','IN_PROGRESS','NOT_DUE']){act('milestone_add');act('milestone_cell',{id:project().milestones.at(-1).id,field:'status',value:status})}const p=project();assert.equal(p.deliverySummary.done,3);assert.equal(p.deliverySummary.percent,60);assert.equal(p.deliverySummary.current.workNo,'4');assert.equal(p.deliverySummary.accepted,0);assert.equal(p.controlSummary.financeRecorded,false)});
test('Payment allocation and atomic paste rollback',()=>{const {act,project,w}=setup();act('milestone_add');act('milestone_add');const [a,b]=project().milestones;const before=JSON.stringify(w.data);assert.throws(()=>act('milestone_cells',{cells:[{id:a.id,field:'paymentPercent',value:'60'},{id:b.id,field:'paymentPercent',value:'50'}]}));assert.equal(JSON.stringify(w.data),before);act('milestone_cells',{cells:[{id:a.id,field:'paymentPercent',value:60},{id:b.id,field:'paymentPercent',value:40},{id:a.id,field:'paymentNo',value:'1'}]});assert.equal(project().paymentSummary.totalPercent,100);assert.equal(project().paymentSummary.groups['1'].amount,null)});
test('NaN and invalid statuses are rejected without audit',()=>{const {act,project,w}=setup();act('milestone_add');const mid=project().milestones[0].id,n=w.data.events.length;for(const value of ['NaN','Infinity',-1,101])assert.throws(()=>act('milestone_cell',{id:mid,field:'paymentPercent',value}));assert.throws(()=>act('milestone_cell',{id:mid,field:'status',value:'fake'}));assert.equal(w.data.events.length,n)});
test('Acceptance and done checklists require evidence',()=>{const {act,project}=setup();act('milestone_add');const mid=project().milestones[0].id;assert.throws(()=>act('milestone_cell',{id:mid,field:'status',value:'ACCEPTED'}));act('milestone_details',{id:mid,status:'ACCEPTED',evidence:'Customer letter'});assert.equal(project().deliverySummary.accepted,1);assert.throws(()=>act('checklist',{id:'project_open',status:'DONE'}));act('checklist',{id:'project_open',status:'DONE',evidence:'Opening approval'});assert.equal(project().checks.project_open.status,'DONE')});
test('Back-to-back allocation/date checks and receipt reversal',()=>{const {record,act,project}=setup();assert.throws(()=>record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',status:'DONE',evidence:'Proof',amount:10,completedDate:'2026-09-30'}));const receipt=record('finance',{kind:'CUSTOMER_PAYMENT',status:'DONE',evidence:'Receipt',amount:100,completedDate:'2026-09-29'});record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',customerPaymentId:receipt.id,status:'DONE',evidence:'Payment',amount:60,completedDate:'2026-09-30'});assert.throws(()=>record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',customerPaymentId:receipt.id,status:'DONE',evidence:'Payment',amount:50,completedDate:'2026-09-30'}));assert.throws(()=>act('control',{...receipt,module:'finance',status:'TODO'}));assert.equal(project().controlSummary.net,40)});
test('Closure gate requires accepted milestones, checks and closed risks',()=>{const {act,record,project}=setup();assert.throws(()=>act('project',{name:'Test',phase:'Closure',completed:true}));for(const phase of ['Acceptance','Billing','Closure'])for(const [id,t,required] of meta.checks[phase])if(required)act('checklist',{id,status:'DONE',evidence:'Verified or N/A reason'});act('project',{name:'Test',phase:'Closure',completed:true});assert.equal(project().completed,true);assert.throws(()=>record('risk'));act('project',{name:'Test',phase:'Closure',completed:false});record('risk');assert.throws(()=>act('project',{name:'Test',phase:'Closure',completed:true}))});
test('Linked documents prevent milestone deletion; comments survive edits',()=>{const {act,record,project}=setup();act('milestone_add');const mid=project().milestones[0].id;record('documents',{relatedId:mid});assert.throws(()=>act('milestone_delete',{id:mid}));const r=record('risk');act('comment',{targetType:'risk',id:r.id,text:'Keep discussion'});act('control',{...r,module:'risk',title:'Revised'});assert.equal(project().controls.risk[0].comments[0].text,'Keep discussion')});
test('Task dependency cycles and premature completion are rejected',()=>{const {act,project}=setup();act('task',{title:'A',owner:'editor',status:'TODO'});const a=project().tasks[0];act('task',{title:'B',owner:'editor',dependencies:[a.id]});const b=project().tasks[1];assert.throws(()=>act('task',{...a,dependencies:[b.id]}));assert.throws(()=>act('task',{...b,status:'DONE'}));act('task',{...a,status:'DONE'});act('task',{...b,status:'DONE'});assert.throws(()=>act('task',{...a,status:'TODO'}))});
test('Last owner and editor invite rules',()=>{const {act,project}=setup();assert.throws(()=>act('member',{user:'owner',role:'REMOVE'}));assert.throws(()=>act('member',{user:'outsider',role:'OWNER'},'editor'));act('project',{name:'Test',phase:'Contract',allowEditorInvites:true});act('member',{user:'outsider',role:'VIEWER'},'editor');assert.equal(project().members.length,4)});
test('Thai calendar dates and current-period controls',()=>{assert.equal(parseDay('9/10/2569'),'2026-10-09');assert.equal(parseDay('2 กรกฎาคม 2569'),'2026-07-02');assert.equal(parseDay('31/2/2569'),null);const p={projectInfo:{signedDate:'2 กรกฎาคม 2569',deliveryDueDate:'29/12/2569'},controls:{procurement:[{id:'r',title:'Vendor',status:'TODO',startDate:'2026-07-01',poDate:'2026-08-01',endDate:'2026-12-29'}]},checks:{}};assert.equal(controlSummary(p,'2026-09-30').alerts.length,4)});
