import test from 'node:test';import assert from 'node:assert/strict';
import {Workspace,meta,Problem,parseDay,deliverySummary,controlSummary,health} from '../lib/pmo/core.mjs';
function setup(){const w=new Workspace({users:['owner','editor','viewer','outsider'],projects:[],members:[],events:[],notifications:[]});w.act('owner','create_project',{name:'Test'});const p=w.data.projects[0];for(const [user,role] of [['editor','EDITOR'],['viewer','VIEWER']])w.act('owner','member',{project:p.id,user,role});const act=(action,d={},user='owner')=>w.act(user,action,{project:p.id,...d}),project=()=>w.state('owner').projects[0];const record=(module,d={})=>{const fields=Object.fromEntries(meta.controlModules[module].fields.map(([k,l,t,choices])=>[k,t==='select'?choices[0]:t==='status'?'TODO':'']));act('control',{...fields,title:'Record',owner:'editor',module,...d});return project().controls[module].at(-1)};return {w,p,act,project,record}}
test('Every lifecycle module persists with audit and assignments',()=>{const {w,record,project}=setup();for(const module of Object.keys(meta.controlModules)){record(module);assert.equal(project().events[0].action,'control')}assert.equal(w.state('editor').notifications.length,Object.keys(meta.controlModules).length)});
test('Viewer and outsider cannot mutate data',()=>{const {act}=setup();for(const user of ['viewer','outsider'])for(const [action,d] of [['milestone_add',{}],['control',{module:'risk'}],['checklist',{id:'project_open',status:'DONE',evidence:'proof'}]])assert.throws(()=>act(action,d,user),e=>e.status===403)});
test('Cross-project state and mention notifications stay isolated',()=>{const {w,act,record}=setup();const r=record('risk');act('comment',{targetType:'risk',id:r.id,text:'@viewer @outsider'});assert.equal(w.state('outsider').projects.length,0);assert.equal(w.state('outsider').notifications.length,0);assert.equal(w.state('viewer').notifications.length,1)});
test('Three delivered milestones mean 60% progress, not acceptance or receipts',()=>{const {act,project}=setup();for(const status of ['DELIVERED','DELIVERED','DELIVERED','IN_PROGRESS','NOT_DUE']){act('milestone_add');act('milestone_cell',{id:project().milestones.at(-1).id,field:'status',value:status})}const p=project();assert.equal(p.deliverySummary.done,3);assert.equal(p.deliverySummary.percent,60);assert.equal(p.deliverySummary.current.workNo,'4');assert.equal(p.deliverySummary.accepted,0);assert.equal(p.controlSummary.financeRecorded,false)});
test('Payment allocation and atomic paste rollback',()=>{const {act,project,w}=setup();act('milestone_add');act('milestone_add');const [a,b]=project().milestones;const before=JSON.stringify(w.data);assert.throws(()=>act('milestone_cells',{cells:[{id:a.id,field:'paymentPercent',value:'60'},{id:b.id,field:'paymentPercent',value:'50'}]}));assert.equal(JSON.stringify(w.data),before);act('milestone_cells',{cells:[{id:a.id,field:'paymentPercent',value:60},{id:b.id,field:'paymentPercent',value:40},{id:a.id,field:'paymentNo',value:'1'}]});assert.equal(project().paymentSummary.totalPercent,100);assert.equal(project().paymentSummary.groups['1'].amount,null)});
test('NaN and invalid statuses are rejected without audit',()=>{const {act,project,w}=setup();act('milestone_add');const mid=project().milestones[0].id,n=w.data.events.length;for(const value of ['NaN','Infinity',-1,101])assert.throws(()=>act('milestone_cell',{id:mid,field:'paymentPercent',value}));assert.throws(()=>act('milestone_cell',{id:mid,field:'status',value:'fake'}));assert.equal(w.data.events.length,n)});
test('Acceptance and done checklists require evidence',()=>{const {act,project}=setup();act('milestone_add');const mid=project().milestones[0].id;assert.throws(()=>act('milestone_cell',{id:mid,field:'status',value:'ACCEPTED'}));act('milestone_details',{id:mid,status:'ACCEPTED',evidence:'Customer letter'});assert.equal(project().deliverySummary.accepted,1);assert.throws(()=>act('checklist',{id:'project_open',status:'DONE'}));act('checklist',{id:'project_open',status:'DONE',evidence:'Opening approval'});assert.equal(project().checks.project_open.status,'DONE')});
test('Back-to-back allocation/date checks and receipt reversal',()=>{const {record,act,project}=setup();assert.throws(()=>record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',status:'DONE',evidence:'Proof',amount:10,completedDate:'2026-09-30'}));const receipt=record('finance',{kind:'CUSTOMER_PAYMENT',status:'DONE',evidence:'Receipt',amount:100,completedDate:'2026-09-29'});record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',customerPaymentId:receipt.id,status:'DONE',evidence:'Payment',amount:60,completedDate:'2026-09-30'});assert.throws(()=>record('finance',{kind:'VENDOR_PAYMENT',condition:'BACK_TO_BACK',customerPaymentId:receipt.id,status:'DONE',evidence:'Payment',amount:50,completedDate:'2026-09-30'}));assert.throws(()=>act('control',{...receipt,module:'finance',status:'TODO'}));assert.equal(project().controlSummary.net,40)});
test('Closure gate requires accepted milestones, checks and closed risks',()=>{const {act,record,project}=setup();assert.throws(()=>act('project',{name:'Test',phase:'Closure',completed:true}));for(const phase of ['Acceptance','Billing','Closure'])for(const [id,t,required] of meta.checks[phase])if(required)act('checklist',{id,status:'DONE',evidence:'Verified or N/A reason'});act('project',{name:'Test',phase:'Closure',completed:true});assert.equal(project().completed,true);assert.throws(()=>record('risk'));act('project',{name:'Test',phase:'Closure',completed:false});record('risk');assert.throws(()=>act('project',{name:'Test',phase:'Closure',completed:true}))});
test('Linked documents prevent milestone deletion; comments survive edits',()=>{const {act,record,project}=setup();act('milestone_add');const mid=project().milestones[0].id;record('documents',{relatedId:mid});assert.throws(()=>act('milestone_delete',{id:mid}));const r=record('risk');act('comment',{targetType:'risk',id:r.id,text:'Keep discussion'});act('control',{...r,module:'risk',title:'Revised'});assert.equal(project().controls.risk[0].comments[0].text,'Keep discussion')});
test('Task dependency cycles and premature completion are rejected',()=>{const {act,project}=setup();act('task',{title:'A',owner:'editor',status:'TODO'});const a=project().tasks[0];act('task',{title:'B',owner:'editor',dependencies:[a.id]});const b=project().tasks[1];assert.throws(()=>act('task',{...a,dependencies:[b.id]}));assert.throws(()=>act('task',{...b,status:'DONE'}));act('task',{...a,status:'DONE'});act('task',{...b,status:'DONE'});assert.throws(()=>act('task',{...a,status:'TODO'}))});
test('Last owner and editor invite rules',()=>{const {act,project}=setup();assert.throws(()=>act('member',{user:'owner',role:'REMOVE'}));assert.throws(()=>act('member',{user:'outsider',role:'OWNER'},'editor'));act('project',{name:'Test',phase:'Contract',allowEditorInvites:true});act('member',{user:'outsider',role:'VIEWER'},'editor');assert.equal(project().members.length,4)});
test('Thai calendar dates and current-period controls',()=>{assert.equal(parseDay('9/10/2569'),'2026-10-09');assert.equal(parseDay('2 กรกฎาคม 2569'),'2026-07-02');assert.equal(parseDay('31/2/2569'),null);const p={projectInfo:{signedDate:'2 กรกฎาคม 2569',deliveryDueDate:'29/12/2569'},controls:{procurement:[{id:'r',title:'Vendor',status:'TODO',startDate:'2026-07-01',poDate:'2026-08-01',endDate:'2026-12-29'}]},checks:{}};assert.equal(controlSummary(p,'2026-09-30').alerts.length,4)});
test('TOR header batch rename keeps stable fields and writes one audit record per changed column',()=>{const {act,project}=setup();act('milestone_add');const id=project().milestones[0].id,before=project().events.length;act('milestone_headers',{labels:[{field:'workNo',label:'ลำดับงาน'},{field:'deliverables',label:'ผลส่งมอบ'}]});const p=project();assert.equal(p.milestoneLabels.workNo,'ลำดับงาน');assert.equal(p.milestoneLabels.deliverables,'ผลส่งมอบ');assert.equal(p.milestones[0].id,id);assert.equal(p.events.length,before+2);assert.deepEqual(JSON.parse(p.events[0].detail),{field:'deliverables',before:'สิ่งส่งมอบ',after:'ผลส่งมอบ'})});
test('System Admin can manage cross-project membership but cannot remove the final owner',()=>{const {w}=setup();w.data.users.push('admin');w.act('owner','create_project',{name:'Second project'});const second=w.data.projects[1];w.act('admin','admin_membership',{project:second.id,user:'outsider',role:'VIEWER'});assert.equal(w.state('outsider').projects[0].role,'VIEWER');assert.equal(w.state('admin').adminProjects.length,2);assert.equal(w.state('admin').adminEvents[0].action,'admin_membership');assert.throws(()=>w.act('admin','admin_membership',{project:second.id,user:'owner',role:'REMOVE'}),e=>e.message.includes('OWNER'));w.act('admin','admin_membership',{project:second.id,user:'outsider',role:'REMOVE'});assert.equal(w.state('outsider').projects.length,0)});
test('My Projects is membership-scoped and Current/Next advance from TOR milestones',()=>{const {w,act,project}=setup();const rows=[];for(const status of ['DELIVERED','DELIVERED','DELIVERED','IN_PROGRESS','NOT_DUE']){act('milestone_add');const row=project().milestones.at(-1);act('milestone_cell',{id:row.id,field:'status',value:status});rows.push(row.id)}let home=w.state('owner');assert.equal(home.projects.length,1);assert.equal(home.projects[0].deliverySummary.current.workNo,'4');assert.equal(home.projects[0].deliverySummary.next.workNo,'5');assert.equal(home.projects[0].deliverySummary.done,3);w.act('editor','create_project',{name:'Separate project'});assert.equal(w.state('owner').projects.length,1);assert.equal(w.state('outsider').projects.length,0);act('milestone_cell',{id:rows[3],field:'status',value:'DELIVERED'});home=w.state('owner');assert.equal(home.projects[0].deliverySummary.current.workNo,'5');assert.equal(home.projects[0].deliverySummary.next,null)});
test('EDITOR can add only new EDITOR/VIEWER members; OWNER manages roles; VIEWER is read-only',()=>{
 const {w,act,project}=setup();
 w.data.users.push('new-editor','owner-added');
 act('member',{user:'new-editor',role:'EDITOR'},'editor');
 act('member',{user:'outsider',role:'VIEWER'},'editor');
 assert.equal(project().members.find(m=>m.user==='new-editor').addedBy,'editor');
 assert.equal(project().members.find(m=>m.user==='new-editor').grantedBy,'editor');
 for(const d of [{user:'viewer',role:'EDITOR'},{user:'owner',role:'REMOVE'},{user:'owner-added',role:'OWNER'}]) assert.throws(()=>act('member',d,'editor'),e=>e.status===403);
 act('member',{user:'owner-added',role:'OWNER'});
 act('member',{user:'new-editor',role:'VIEWER'});
 assert.equal(project().members.find(m=>m.user==='new-editor').addedBy,'editor');
 assert.equal(project().members.find(m=>m.user==='new-editor').grantedBy,'owner');
 act('member',{user:'new-editor',role:'REMOVE'});
 assert.equal(project().members.some(m=>m.user==='new-editor'),false);
 act('member',{user:'owner-added',role:'REMOVE'});
 assert.throws(()=>act('member',{user:'owner',role:'REMOVE'}),e=>e.message.includes('OWNER'));
 assert.throws(()=>act('member',{user:'outsider',role:'VIEWER'},'viewer'),e=>e.status===403);
});
test('EDITOR can rename headers and edit a cell without changing stable row data; audit records actor and time',()=>{const {w,act,project}=setup();act('milestone_add');const row=project().milestones[0];act('milestone_cell',{id:row.id,field:'deliverables',value:'Original delivery text'},'editor');act('milestone_headers',{labels:[{field:'deliverables',label:'Planned Delivery'}]},'editor');const p=project(),event=w.data.events.at(-1);assert.equal(p.milestoneLabels.deliverables,'Planned Delivery');assert.equal(p.milestones[0].id,row.id);assert.equal(p.milestones[0].deliverables,'Original delivery text');assert.throws(()=>act('milestone_headers',{labels:[{field:'deliverables',label:'Viewer edit'}]},'viewer'),e=>e.status===403);assert.throws(()=>act('milestone_cell',{id:row.id,field:'deliverables',value:'Viewer overwrite'},'viewer'),e=>e.status===403);assert.equal(event.actor,'editor');assert.ok(event.at);assert.deepEqual(JSON.parse(event.detail),{field:'deliverables',before:'สิ่งส่งมอบ',after:'Planned Delivery'})});
test('Structured handover preserves legacy notes and records a complete audit event',()=>{const {w,act,project}=setup();w.data.projects[0].handover='Old handover notes';act('handover',{details:{status:'กำลังดำเนินงาน',done:'ส่งมอบแล้ว 3 งวด',remaining:'ทดสอบ SIT',next:'ทดสอบร่วมกับลูกค้า',waiting:'รอ UAT account',links:'https://docs.example/plan'}});const p=project();assert.equal(p.handover,'Old handover notes');assert.equal(p.handoverDetails.done,'ส่งมอบแล้ว 3 งวด');assert.equal(p.handoverDetails.next,'ทดสอบร่วมกับลูกค้า');assert.equal(w.data.events.at(-1).action,'handover');assert.equal(JSON.parse(w.data.events.at(-1).detail).after.links,'https://docs.example/plan')});
test('System Admin membership changes retain membership history and audit each project-wide action',()=>{const {w}=setup();w.data.users.push('admin');w.act('owner','create_project',{name:'Admin managed'});const p=w.data.projects[1];w.act('admin','admin_membership',{project:p.id,user:'outsider',role:'VIEWER'});const added=w.data.members.find(m=>m.project===p.id&&m.user==='outsider');assert.equal(added.addedBy,'admin');assert.equal(added.grantedBy,'admin');w.act('admin','admin_membership',{project:p.id,user:'outsider',role:'EDITOR'});const changed=w.data.members.find(m=>m.project===p.id&&m.user==='outsider');assert.equal(changed.addedBy,'admin');assert.equal(changed.grantedBy,'admin');assert.equal(w.data.events.filter(e=>e.action==='admin_membership').length,4);assert.throws(()=>w.act('admin','admin_membership',{project:p.id,user:'owner',role:'REMOVE'}),e=>e.message.includes('OWNER'))});

test('Multiple vendor contracts and customer LSF persist independently with audited edits',()=>{
 const {w,act,project,record}=setup();
 act('project_info',{contractNo:'CUSTOMER-01',lsfNo:'LSF-CUSTOMER'});
 const first=record('procurement',{kind:'VENDOR_CONTRACT',vendor:'Vendor A',reference:'VA-01',lsfNo:'LSF-A',title:'Contract A'});
 const second=record('procurement',{kind:'VENDOR_CONTRACT',vendor:'Vendor B',reference:'VB-01',lsfNo:'LSF-B',title:'Contract B'});
 act('control',{...first,module:'procurement',lsfNo:'LSF-A-UPDATED'});
 const reloaded=new Workspace(JSON.parse(JSON.stringify(w.data))).state('owner').projects[0];
 assert.equal(reloaded.projectInfo.contractNo,'CUSTOMER-01');
 assert.equal(reloaded.projectInfo.lsfNo,'LSF-CUSTOMER');
 assert.equal(reloaded.controls.procurement.length,2);
 assert.equal(reloaded.controls.procurement.find(r=>r.id===first.id).lsfNo,'LSF-A-UPDATED');
 assert.equal(reloaded.controls.procurement.find(r=>r.id===second.id).lsfNo,'LSF-B');
 const audit=JSON.parse(reloaded.events[0].detail);
 assert.equal(audit.before.lsfNo,'LSF-A');assert.equal(audit.after.lsfNo,'LSF-A-UPDATED');
});


test('Health links resolve to the exact blocker, reminder or TOR page',()=>{
 const {p,act,record}=setup();
 assert.deepEqual(health(p).target,{view:'tor'});
 act('task',{title:'Blocked task',owner:'owner',status:'BLOCKED',waiting:'Approval'});
 let target=health(p).target;assert.equal(target.type,'task');assert.equal(target.id,p.tasks[0].id);
 p.tasks=[];act('milestone_add');act('milestone_details',{id:p.milestones[0].id,status:'BLOCKED',waiting:'Customer'});
 assert.deepEqual(health(p).target,{view:'tor',type:'milestone',id:p.milestones[0].id});
 p.milestones=[];const r=record('procurement',{kind:'VENDOR_CONTRACT',status:'BLOCKED',notes:'Waiting vendor'});
 assert.deepEqual(health(p).target,{view:'procurement',type:'control',id:r.id});
 p.controls.procurement=[];p.projectInfo.signedDate='2000-01-01';
 assert.deepEqual(health(p).target,{view:'opening',type:'control',kind:'STAMP_DUTY'});
 record('opening',{kind:'STAMP_DUTY',status:'DONE',evidence:'Receipt'});
 assert.deepEqual(health(p).target,{view:'lifecycle',type:'checklist',phase:'Planning',id:'risk_assessment'});
});
